/* ==========================================================================
   NIMCO'S PRODUCT DATA REPOSITORY (ALL 15 AUTHENTIC SNACKS)
   Professional FMCG Edition: Authentic culinary specifications,
   accurate nutritional data, and 100% Pure Vegetarian certification.
   ========================================================================== */

const NIMCO_PRODUCTS = [
  {
    id: "pop-corn",
    name: "Nimco's Butter Salted Pop Corn",
    tagline: "Light and Fluffy Golden Corn with Rich Butter Note",
    category: "bestsellers",
    categoryLabel: "Bestsellers",
    price: 5,
    packWeight: "25g",
    image: "assets/pop-corn.png",
    crunchLevel: "Crispy Light",
    crunchStars: 4,
    spiceLevel: "Zero Spice",
    flavorHeroBadge: "Butter Salted",
    badgeBg: "var(--brand-red)",
    snackMoments: "Family gatherings, tea time, and light evening refreshment.",
    funBite: "Golden corn kernels popped to airy lightness with rich creamy butter aroma and fine salt.",
    flavorProfile: { crunch: 4, spice: 1, sweet: 2, tangy: 1, salty: 4 },
    flavorTags: ["Butter Salted", "Golden Corn", "Zero Trans Fat"],
    badge: "Bestseller",
    accentColor: "#FFF8E7",
    desc: "Golden corn kernels popped to airy lightness and finished with rich creamy melted butter and fine salt. A beloved staple for family gatherings and evening tea.",
    culinaryNote: "Selected high-expansion corn kernels hot-air popped for supreme crispness and zero trans-fat snacking.",
    nutrition: {
      calories: "115 kcal",
      protein: "2.5g",
      carbs: "16g",
      fiber: "2.8g",
      fat: "4.5g"
    },
    ingredients: "Select Golden Corn, Edible Vegetable Oil, Iodized Salt, Creamy Butter Flavor, Turmeric."
  },
  {
    id: "aloo-bhujia",
    name: "Nimco's Royal Aloo Bhujia",
    tagline: "Crisp Potato Strands Seasoned with Heritage Spices",
    category: "bestsellers",
    categoryLabel: "Bestsellers",
    price: 5,
    packWeight: "35g",
    image: "assets/aloo-bhujia.png",
    crunchLevel: "Super Crunchy",
    crunchStars: 5,
    spiceLevel: "Mild Chatpata",
    flavorHeroBadge: "Royal Aloo Bhujia",
    badgeBg: "var(--brand-red)",
    snackMoments: "Sprinkled over poha, paired with afternoon tea, or enjoyed directly from the pack.",
    funBite: "Finely spun potato noodles seasoned with fresh mint, black pepper, and dry mango.",
    flavorProfile: { crunch: 5, spice: 3, sweet: 1, tangy: 4, salty: 4 },
    flavorTags: ["Export Quality", "Potato Crisp", "Bikaneri Recipe"],
    badge: "Bestseller",
    accentColor: "#FFEBEB",
    desc: "Finely spun strands of premium farm potatoes blended with chickpea flour and signature spices. Crisp, delicate strands that melt on the tongue.",
    culinaryNote: "Crafted following authentic Bikaneri formulation using fresh potato mash, moth dal, and aromatic royal spices.",
    nutrition: {
      calories: "145 kcal",
      protein: "3.2g",
      carbs: "14g",
      fiber: "1.9g",
      fat: "8.5g"
    },
    ingredients: "Fresh Potato Mash, Gram Flour (Besan), Dew Bean Flour (Moth Dal), Edible Vegetable Oil, Mint, Red Chilli, Black Salt, Mango Powder."
  },
  {
    id: "khatta-meetha",
    name: "Nimco's Khatta Meetha Mixture",
    tagline: "Balanced Sweet and Tangy Medley of Sev and Boondi",
    category: "bestsellers",
    categoryLabel: "Bestsellers",
    price: 5,
    packWeight: "35g",
    image: "assets/khatta_meetha.png",
    crunchLevel: "Multi Crunch",
    crunchStars: 5,
    spiceLevel: "Sweet & Tangy",
    flavorHeroBadge: "Sweet & Tangy",
    badgeBg: "var(--brand-red)",
    snackMoments: "Travel snack, afternoon tea companion, and festive sharing.",
    funBite: "Sweet caramelized boondi drops balanced against crisp spiced sev and roasted peanuts.",
    flavorProfile: { crunch: 5, spice: 2, sweet: 4, tangy: 5, salty: 3 },
    flavorTags: ["Sweet & Tangy", "Crisp Sev", "Golden Boondi"],
    badge: "Bestseller",
    accentColor: "#FFF0EB",
    desc: "A harmonious medley of crispy golden sev ribbons, roasted peanuts, sweet boondi drops, and puffed rice tossed in an amchur sweet-sour seasoning.",
    culinaryNote: "A traditional balance of dry mango powder, jaggery notes, and crunchy pulses honoring classic Indian taste traditions.",
    nutrition: {
      calories: "150 kcal",
      protein: "3.5g",
      carbs: "18g",
      fiber: "2.1g",
      fat: "7.8g"
    },
    ingredients: "Gram Flour, Peanuts, Puffed Rice, Sugar Glaze, Edible Vegetable Oil, Sago pearls, Dry Mango Powder (Amchur), Rock Salt."
  },
  {
    id: "tasty-peanuts",
    name: "Nimco's Tasty Besan Coated Peanuts",
    tagline: "Double-Layer Spiced Batter Crust with Whole Peanuts",
    category: "peanuts",
    categoryLabel: "Peanuts & Nuts",
    price: 5,
    packWeight: "30g",
    image: "assets/Tasty.png",
    crunchLevel: "Max Crunch",
    crunchStars: 5,
    spiceLevel: "Chatpata Crunch",
    flavorHeroBadge: "Besan Coated Peanuts",
    badgeBg: "var(--brand-red)",
    snackMoments: "Midday energy recharge, travel, and tea time.",
    funBite: "Crisp besan jacket wrapped around select roasted Gujarat groundnuts.",
    flavorProfile: { crunch: 5, spice: 3, sweet: 1, tangy: 3, salty: 4 },
    flavorTags: ["High Protein", "Besan Crust", "Whole Peanuts"],
    badge: "Top Pick",
    accentColor: "#FFF5E5",
    desc: "Plump roasted groundnuts generously coated in a spiced gram flour batter and fried until crispy. Rich, savory, and robustly textured.",
    culinaryNote: "Double-coated using stone-ground chickpea flour with asafoetida and pink rock salt for deep savory complexity.",
    nutrition: {
      calories: "162 kcal",
      protein: "5.8g",
      carbs: "11g",
      fiber: "2.5g",
      fat: "10.2g"
    },
    ingredients: "Selected Roasted Peanuts, Gram Flour (Besan), Corn Starch, Red Chilli Powder, Cumin, Black Pepper, Asafoetida, Vegetable Oil, Pink Salt."
  },
  {
    id: "masala-peanuts",
    name: "Nimco's Chatpata Masala Peanuts",
    tagline: "Roasted Groundnuts Tossed in Aromatic Desi Spices",
    category: "peanuts",
    categoryLabel: "Peanuts & Nuts",
    price: 5,
    packWeight: "35g",
    image: "assets/masala_peanuts.png",
    crunchLevel: "Hard Crunch",
    crunchStars: 5,
    spiceLevel: "Zesty Masala",
    flavorHeroBadge: "Zesty Masala Peanuts",
    badgeBg: "var(--brand-red)",
    snackMoments: "Rainy afternoons with hot ginger tea.",
    funBite: "Slow roasted whole peanuts dusted in pure black pepper, clove, and Himalayan black salt.",
    flavorProfile: { crunch: 5, spice: 4, sweet: 1, tangy: 4, salty: 4 },
    flavorTags: ["Spiced Peanuts", "Desi Masala", "High Protein"],
    badge: "Zesty Punch",
    accentColor: "#FFE8E8",
    desc: "Slow-roasted golden peanuts tossed in black pepper, cloves, dried mango, and Himalayan black salt for an authentic spicy punch.",
    culinaryNote: "Dry-roasted at controlled temperatures to ensure uniform crispness before tumbling with fresh spice blends.",
    nutrition: {
      calories: "168 kcal",
      protein: "6.2g",
      carbs: "9g",
      fiber: "2.7g",
      fat: "11.0g"
    },
    ingredients: "Whole Roasted Peanuts, Refined Palmolein Oil, Black Salt, Dry Mango Powder, Cumin Seeds, Ground Spices."
  },
  {
    id: "salted-peanuts",
    name: "Nimco's Golden Salted Peanuts",
    tagline: "Pure Roasted Groundnuts with Natural Rock Salt",
    category: "peanuts",
    categoryLabel: "Peanuts & Nuts",
    price: 5,
    packWeight: "35g",
    image: "assets/salted_peanuts.png",
    crunchLevel: "Classic Snap",
    crunchStars: 4,
    spiceLevel: "Mild Salted",
    flavorHeroBadge: "Salted Peanuts",
    badgeBg: "var(--brand-red)",
    snackMoments: "Wholesome midday energy recharge and light snack.",
    funBite: "Wholesome roasted groundnuts seasoned with pure crystal salt.",
    flavorProfile: { crunch: 4, spice: 1, sweet: 1, tangy: 1, salty: 4 },
    flavorTags: ["Pure & Simple", "Mild Salted", "High Protein"],
    badge: "Classic Salted",
    accentColor: "#FFFDF0",
    desc: "Wholesome blanched peanuts roasted to a warm golden tone and lightly sprinkled with pure iodized salt. Clean, wholesome energy in every bite.",
    culinaryNote: "Evenly blanched and roasted without excess oil, keeping the natural groundnut flavor front and center.",
    nutrition: {
      calories: "165 kcal",
      protein: "6.4g",
      carbs: "8g",
      fiber: "2.6g",
      fat: "11.2g"
    },
    ingredients: "Select Roasted Peanuts, Edible Vegetable Oil, Pure Iodized Salt."
  },
  {
    id: "moong-dal",
    name: "Nimco's Crispy Salted Moong Dal",
    tagline: "Split Yellow Pulses Light and Crisp with Rock Salt",
    category: "dals",
    categoryLabel: "Crunchy Dals",
    price: 5,
    packWeight: "35g",
    image: "assets/moong_dal.png",
    crunchLevel: "Light Crunch",
    crunchStars: 5,
    spiceLevel: "Mild Salted",
    flavorHeroBadge: "Crispy Moong Dal",
    badgeBg: "var(--brand-red)",
    snackMoments: "Light teatime snack and everyday nutritious munching.",
    funBite: "Golden split pulses flash-fried for an ethereal crisp that melts cleanly in seconds.",
    flavorProfile: { crunch: 5, spice: 1, sweet: 1, tangy: 1, salty: 4 },
    flavorTags: ["Protein Rich", "Light & Crisp", "Zero Cholesterol"],
    badge: "Light & Crisp",
    accentColor: "#FFF9DB",
    desc: "Split yellow moong dal lentils fried to an ethereal lightness and dusted with rock salt. Clean, delicate, and easy to digest.",
    culinaryNote: "Soaked, dried, and flash-fried in small batches to preserve the natural protein structure and distinct golden color.",
    nutrition: {
      calories: "135 kcal",
      protein: "5.1g",
      carbs: "17g",
      fiber: "2.2g",
      fat: "6.0g"
    },
    ingredients: "Green Gram Split (Moong Dal), Edible Vegetable Oil, Iodized Salt, Black Pepper."
  },
  {
    id: "chana-dal",
    name: "Nimco's Spicy Chana Dal",
    tagline: "Hearty Bengal Gram with Zesty Chatpata Spices",
    category: "dals",
    categoryLabel: "Crunchy Dals",
    price: 5,
    packWeight: "35g",
    image: "assets/chana_dal.png",
    crunchLevel: "Firm Crunch",
    crunchStars: 5,
    spiceLevel: "Chatpata Zing",
    flavorHeroBadge: "Spicy Chana Dal",
    badgeBg: "var(--brand-red)",
    snackMoments: "Protein-rich evening snack and tea accompaniment.",
    funBite: "Bold golden lentils seasoned with amchur, cumin, and Rajasthani spice blend.",
    flavorProfile: { crunch: 5, spice: 4, sweet: 1, tangy: 4, salty: 4 },
    flavorTags: ["Fiber Rich", "Bengal Gram", "Hearty Crunch"],
    badge: "Spicy Dal",
    accentColor: "#FFF3DC",
    desc: "Golden split Bengal gram fried until satisfyingly crunchy and dusted with red chili, amchur, and fragrant garam masala.",
    culinaryNote: "Selected large-kernel Bengal gram split lentils delivering bold texture and hearty plant fiber.",
    nutrition: {
      calories: "140 kcal",
      protein: "5.4g",
      carbs: "16g",
      fiber: "3.1g",
      fat: "6.8g"
    },
    ingredients: "Split Bengal Gram (Chana Dal), Edible Vegetable Oil, Red Chilli Powder, Dry Mango, Cumin, Black Salt."
  },
  {
    id: "hing-chana",
    name: "Nimco's Hing Roasted Chana",
    tagline: "Aromatic Asafoetida and Dry-Roasted Chickpeas",
    category: "dals",
    categoryLabel: "Crunchy Dals",
    price: 5,
    packWeight: "35g",
    image: "assets/hing_chana.png",
    crunchLevel: "Solid Crunch",
    crunchStars: 5,
    spiceLevel: "Aromatic Savory",
    flavorHeroBadge: "Hing Roasted Chana",
    badgeBg: "var(--brand-red)",
    snackMoments: "Traditional teatime companion and wholesome digestive snack.",
    funBite: "Dry-roasted brown chickpeas infused with authentic Hathras hing for fragrant digestive comfort.",
    flavorProfile: { crunch: 5, spice: 2, sweet: 1, tangy: 2, salty: 3 },
    flavorTags: ["Digestive Spices", "Roasted Chana", "Pure Hing"],
    badge: "Hing Roasted",
    accentColor: "#F4F7EB",
    desc: "Crunchy dry-roasted brown chickpeas seasoned with aromatic Hing (asafoetida) and warm ground spices. Excellent digestive qualities.",
    culinaryNote: "Naturally high in dietary fiber and prepared with premium Hathras asafoetida for gut-friendly digestive comfort.",
    nutrition: {
      calories: "130 kcal",
      protein: "5.6g",
      carbs: "18g",
      fiber: "4.0g",
      fat: "4.2g"
    },
    ingredients: "Roasted Bengal Gram (Chana), Pure Asafoetida (Hing), Rock Salt, Black Pepper, Cumin, Light Vegetable Oil."
  },
  {
    id: "matar",
    name: "Nimco's Chatpata Green Peas",
    tagline: "Dehydrated Garden Peas with Tangy Chaat Spices",
    category: "dals",
    categoryLabel: "Crunchy Dals",
    price: 5,
    packWeight: "35g",
    image: "assets/Matar.png",
    crunchLevel: "Crispy Pop",
    crunchStars: 4,
    spiceLevel: "Tangy Chatpata",
    flavorHeroBadge: "Chatpata Green Peas",
    badgeBg: "var(--brand-red)",
    snackMoments: "Party platter mix-ins, bhel puri topping, and crisp teatime bites.",
    funBite: "Sweet garden peas turned into crunchy bites with zesty chaat masala.",
    flavorProfile: { crunch: 4, spice: 3, sweet: 2, tangy: 5, salty: 4 },
    flavorTags: ["Garden Peas", "Tangy Seasoning", "High Fiber"],
    badge: "Tangy Peas",
    accentColor: "#E8F8EE",
    desc: "Sweet garden green peas dried and fried to an airy crunch, then tossed with tangy amchur, cumin, and rock salt.",
    culinaryNote: "Gradually dehydrated garden peas seasoned with chatpata masala for a satisfying pop in every spoonful.",
    nutrition: {
      calories: "128 kcal",
      protein: "4.2g",
      carbs: "17g",
      fiber: "3.6g",
      fat: "4.8g"
    },
    ingredients: "Dehydrated Green Peas, Edible Vegetable Oil, Dry Mango Powder, Cumin, Iodized Salt, Chaat Masala."
  },
  {
    id: "tikha-mitha-mix",
    name: "Nimco's Tikha Mitha Mixture",
    tagline: "Medley of Spiced Sev, Sweet Boondi, and Lentils",
    category: "mixes",
    categoryLabel: "Chatpata Mixes",
    price: 5,
    packWeight: "35g",
    image: "assets/tikha_mitha_mix.png",
    crunchLevel: "Multi Crunch",
    crunchStars: 5,
    spiceLevel: "Mild Spicy & Sweet",
    flavorHeroBadge: "Tikha Mitha Mix",
    badgeBg: "var(--brand-red)",
    snackMoments: "Festive occasions, family tea time, and celebrations.",
    funBite: "Curry leaves, golden peanuts, and spiced ribbon sev balanced with sweet boondi drops.",
    flavorProfile: { crunch: 5, spice: 3, sweet: 3, tangy: 4, salty: 4 },
    flavorTags: ["Party Mix", "Curry Leaves", "Classic Recipe"],
    badge: "Family Favorite",
    accentColor: "#FFEFE5",
    desc: "A timeless Indian favorite combining spiced sev ribbons, tender sweet boondi, crunchy lentils, and curry leaf flakes.",
    culinaryNote: "The signature contrast of red chili and caramelized sugar droplets creates our bestselling festive blend.",
    nutrition: {
      calories: "148 kcal",
      protein: "3.4g",
      carbs: "19g",
      fiber: "2.0g",
      fat: "7.2g"
    },
    ingredients: "Gram Flour, Rice Flakes, Sweet Drops (Boondi), Groundnuts, Curry Leaves, Sugar, Red Chilli, Spices, Vegetable Oil."
  },
  {
    id: "corn-mix",
    name: "Nimco's Golden Corn Flake Mix",
    tagline: "Crisp Roasted Corn Flakes with Groundnuts",
    category: "mixes",
    categoryLabel: "Chatpata Mixes",
    price: 5,
    packWeight: "30g",
    image: "assets/corn_mix.png",
    crunchLevel: "Feather Crisp",
    crunchStars: 4,
    spiceLevel: "Tangy Mild",
    flavorHeroBadge: "Corn Flake Mix",
    badgeBg: "var(--brand-red)",
    snackMoments: "Light afternoon tea companion and non-greasy snacking.",
    funBite: "Ultra-crisp roasted corn flakes tossed with crunchy peanuts and sweet-and-sour amchur.",
    flavorProfile: { crunch: 4, spice: 2, sweet: 3, tangy: 4, salty: 3 },
    flavorTags: ["Golden Corn", "Roasted Nuts", "Sweet & Salty"],
    badge: "Corn Crunch",
    accentColor: "#FFFBE6",
    desc: "Crisp corn flakes tossed with crunchy roasted groundnuts, seasoned lightly with chatpata amchur and cumin.",
    culinaryNote: "Carefully roasted corn flakes blended with whole peanuts for a delicate, non-greasy tea-time crunch.",
    nutrition: {
      calories: "138 kcal",
      protein: "3.0g",
      carbs: "19g",
      fiber: "2.4g",
      fat: "6.1g"
    },
    ingredients: "Corn Flakes, Peanuts, Puffed Gram, Edible Vegetable Oil, Sugar, Amchur, Cumin, Black Salt."
  },
  {
    id: "dal-chawal",
    name: "Nimco's Dal Chawal Crispy Crunch",
    tagline: "Puffed Rice and Roasted Lentils Savory Blend",
    category: "mixes",
    categoryLabel: "Chatpata Mixes",
    price: 5,
    packWeight: "30g",
    image: "assets/dal_chawal.png",
    crunchLevel: "Breezy Snap",
    crunchStars: 4,
    spiceLevel: "Savory Mild",
    flavorHeroBadge: "Dal Chawal Crunch",
    badgeBg: "var(--brand-red)",
    snackMoments: "Light tea breaks and between-meal munching.",
    funBite: "Airy puffed rice pearls and roasted lentils with roasted turmeric and jeera seasoning.",
    flavorProfile: { crunch: 4, spice: 2, sweet: 1, tangy: 2, salty: 4 },
    flavorTags: ["Air Light", "Savory Crunch", "Tea Companion"],
    badge: "Crispy Rice",
    accentColor: "#F4F6F9",
    desc: "Puffed golden rice crispies tossed with roasted lentils, turmeric, cumin, and mild rock salt. Light and crisp.",
    culinaryNote: "Inspired by traditional puffed grain recipes, prepared with minimal oil for light everyday snacking.",
    nutrition: {
      calories: "122 kcal",
      protein: "3.2g",
      carbs: "20g",
      fiber: "1.8g",
      fat: "4.0g"
    },
    ingredients: "Puffed Rice, Roasted Lentils, Chickpea Flour crisps, Refined Palmolein Oil, Salt, Turmeric, Cumin."
  },
  {
    id: "salted-pope",
    name: "Nimco's Salted Pope Crispies",
    tagline: "Delicate Crispy Puffs with Mellow Sea Salt",
    category: "mixes",
    categoryLabel: "Chatpata Mixes",
    price: 5,
    packWeight: "25g",
    image: "assets/salted_pope.png",
    crunchLevel: "Melt-In-Mouth",
    crunchStars: 4,
    spiceLevel: "Zero Spice",
    flavorHeroBadge: "Salted Crispies",
    badgeBg: "var(--brand-red)",
    snackMoments: "Gentle finger snacks for all ages and family travel.",
    funBite: "Crispy hollow tubes seasoned with pure salt. Gentle and airy.",
    flavorProfile: { crunch: 3, spice: 1, sweet: 1, tangy: 1, salty: 4 },
    flavorTags: ["Crispy Puffs", "Melt-In-Mouth", "Light Snack"],
    badge: "Light Crispies",
    accentColor: "#F0F4FF",
    desc: "Crispy tubular grain puffs seasoned with pure sea salt. Light as air, crispy, and mild.",
    culinaryNote: "Extruded at high pressure and oven-baked for a zero-mess, airy crunch enjoyed by all ages.",
    nutrition: {
      calories: "110 kcal",
      protein: "2.1g",
      carbs: "18g",
      fiber: "1.2g",
      fat: "4.2g"
    },
    ingredients: "Wheat Flour, Corn Starch, Vegetable Oil, Natural Sea Salt, Leavening agents."
  },
  {
    id: "jeera-papad",
    name: "Nimco's Traditional Jeera Papad",
    tagline: "Sun-Dried Lentil Wafers with Whole Cumin Seeds",
    category: "papad",
    categoryLabel: "Jeera Papad",
    price: 10,
    packWeight: "100g",
    image: "assets/jeera-papad.png",
    crunchLevel: "Extreme Crisp",
    crunchStars: 5,
    spiceLevel: "Aromatic Cumin",
    flavorHeroBadge: "Jeera Papad",
    badgeBg: "var(--brand-red)",
    snackMoments: "Lunch and dinner thalis, festive celebrations, roasted or fried.",
    funBite: "Wafer-thin urad dal dough loaded with whole fragrant cumin seeds and black pepper.",
    flavorProfile: { crunch: 5, spice: 3, sweet: 1, tangy: 1, salty: 4 },
    flavorTags: ["Sun Dried", "Whole Jeera", "Roast or Fry"],
    badge: "Authentic Recipe",
    accentColor: "#FFFDF2",
    desc: "Authentic handmade thin lentil wafers generously studded with whole fragrant cumin seeds. Roast over an open flame or fry for celebratory meals.",
    culinaryNote: "Rolled from stone-ground urad and moong dal flours and sun-cured according to artisanal Rajasthani papad standards.",
    nutrition: {
      calories: "92 kcal per pc",
      protein: "4.5g",
      carbs: "14g",
      fiber: "2.9g",
      fat: "0.8g"
    },
    ingredients: "Urad Dal Flour, Moong Dal Flour, Whole Cumin Seeds (Jeera), Black Pepper, Asafoetida, Papad Khar, Edible Salt."
  }
];

if (typeof window !== 'undefined') {
  window.NIMCO_PRODUCTS = NIMCO_PRODUCTS;
}
