/* ==========================================================================
   NIMCO'S PRODUCT DATA REPOSITORY (ALL 15 AUTHENTIC SNACKS)
   Includes accurate images from assets/, prices, categories, and nutrition facts
   ========================================================================== */

const NIMCO_PRODUCTS = [
  {
    id: "pop-corn",
    name: "Nimco's Butter Salted Pop Corn",
    tagline: "Super Fluffy & Melt-in-Mouth Butter Joy!",
    category: "kids-fav",
    categoryLabel: "Kids Favorite",
    price: 5,
    packWeight: "25g",
    image: "assets/pop-corn.png",
    crunchLevel: "Crispy Light",
    crunchStars: 4,
    spiceLevel: "Zero Spice",
    flavorTags: ["Butter Salted", "Super Fluffy", "Kids Favorite"],
    badge: "Bestseller 🌟",
    accentColor: "#F4E8FF",
    desc: "Golden American corn kernels popped to fluffy cloud perfection and kissed with creamy melted butter and fine salt. The ultimate companion for cartoon time and school study breaks!",
    kidFact: "Did you know? Popcorn kernels have a tiny drop of water trapped inside that goes POP when heated! 🍿",
    nutrition: {
      calories: "115 kcal",
      protein: "2.5g",
      carbs: "16g",
      fiber: "2.8g",
      fat: "4.5g"
    },
    ingredients: "Select Golden Corn, Edible Vegetable Oil, Iodized Salt, Creamy Butter Flavor, Turmeric."
  },
  {
    id: "aloo-bhujia",
    name: "Nimco's Royal Aloo Bhujia",
    tagline: "For Every Special Treat - Crisp & Crunchy!",
    category: "kids-fav",
    categoryLabel: "Kids Favorite",
    price: 5,
    packWeight: "35g",
    image: "assets/aloo-bhujia.png",
    crunchLevel: "Super Crunchy",
    crunchStars: 5,
    spiceLevel: "Mild Chatpata",
    flavorTags: ["Export Quality", "Potato Crisp", "Crispy Noodles"],
    badge: "All-Time Hero 👑",
    accentColor: "#FFEBEB",
    desc: "Finely spun strands of farm-fresh potatoes blended with premium chickpea flour and secret royal spices. Irresistibly crisp strands that vanish the moment you open the pack!",
    kidFact: "Aloo Bhujia was first created over 100 years ago in Rajasthan and is now India's most beloved snack! 🥔",
    nutrition: {
      calories: "145 kcal",
      protein: "3.2g",
      carbs: "14g",
      fiber: "1.9g",
      fat: "8.5g"
    },
    ingredients: "Fresh Potato Mash, Gram Flour (Besan), Dew Bean Flour (Moth Dal), Edible Vegetable Oil, Mint, Red Chilli, Black Salt, Mango Powder."
  },
  {
    id: "khatta-meetha",
    name: "Nimco's Khatta Meetha Mixture",
    tagline: "Khate Khate Mann Na Bhare - Sweet & Tangy!",
    category: "kids-fav",
    categoryLabel: "Kids Favorite",
    price: 5,
    packWeight: "35g",
    image: "assets/khatta_meetha.jpeg",
    crunchLevel: "Mega Crunch",
    crunchStars: 5,
    spiceLevel: "Sweet & Tangy",
    flavorTags: ["Khate Khate Mann Na Bhare", "Tangy Delight", "Sweet Sev"],
    badge: "Iconic Flavor ❤️",
    accentColor: "#FFF0EB",
    desc: "A magical party in every mouthful! Crispy golden sev, crunchy roasted peanuts, sweet boondi, and puffed rice tossed in a mouthwatering sweet & tangy amchur glaze.",
    kidFact: "The word 'Khatta Meetha' means tangy and sweet at the exact same second! 🍬🍋",
    nutrition: {
      calories: "150 kcal",
      protein: "3.5g",
      carbs: "18g",
      fiber: "2.1g",
      fat: "7.8g"
    },
    ingredients: "Gram Flour, Peanuts, Puffed Rice, Sugar Glaze, Edible Vegetable Oil, Sago pearls, Dry Mango Powder (Amchur), Rock Salt."
  },
  {
    id: "tasty-peanuts",
    name: "Nimco's Tasty Besan Coated Peanuts",
    tagline: "Double Layer Crunchy Nutty Joy!",
    category: "peanuts",
    categoryLabel: "Peanut Power",
    price: 5,
    packWeight: "30g",
    image: "assets/Tasty.png",
    crunchLevel: "Max Crunch",
    crunchStars: 5,
    spiceLevel: "Chatpata Crunch",
    flavorTags: ["High Protein", "Besan Crust", "Double Crunch"],
    badge: "Snack Champ 🥜",
    accentColor: "#FFF5E5",
    desc: "Plump, premium roasted groundnuts double-coated in a spiced gram flour batter and fried until ultra-crisp. Super crunchy on the outside, rich and nutty on the inside!",
    kidFact: "Peanuts are actually legumes, meaning they grow underground like secret treasures! 🌱",
    nutrition: {
      calories: "162 kcal",
      protein: "5.8g",
      carbs: "11g",
      fiber: "2.5g",
      fat: "10.2g"
    },
    ingredients: "Selected Roasted Peanuts, Gram Flour (Besan), Corn Starch, Red Chilli Powder, Cumin, Black Pepper, Asafoetida, Vegetable Oil, Pink Salt."
  },
  {
    id: "masala-peanuts",
    name: "Nimco's Chatpata Masala Peanuts",
    tagline: "Zesty Indian Spices on Crunchy Groundnuts",
    category: "peanuts",
    categoryLabel: "Peanut Power",
    price: 5,
    packWeight: "35g",
    image: "assets/masala_peanuts.png",
    crunchLevel: "Hard Crunch",
    crunchStars: 5,
    spiceLevel: "Zesty Masala",
    flavorTags: ["Energy Boost", "Desi Masala", "Crunch Monster"],
    badge: "Spice Kick 🔥",
    accentColor: "#FFE8E8",
    desc: "Oven-roasted golden peanuts dusted with a mouth-watering blend of black pepper, clove, dried mango, and Himalayan black salt for that unforgettable chatpata punch.",
    kidFact: "Eating a handful of peanuts gives athletes and superheroes instant energy for playgrounds! ⚡",
    nutrition: {
      calories: "168 kcal",
      protein: "6.2g",
      carbs: "9g",
      fiber: "2.7g",
      fat: "11.0g"
    },
    ingredients: "Whole Roasted Peanuts, Refined Palmolein Oil, Black Salt, Dry Mango Powder, Cumin Seeds, Ground Spices."
  },
  {
    id: "salted-peanuts",
    name: "Nimco's Golden Salted Peanuts",
    tagline: "Pure, Roasted Groundnut Crunch with Himalayan Salt",
    category: "peanuts",
    categoryLabel: "Peanut Power",
    price: 5,
    packWeight: "35g",
    image: "assets/salted_peanuts.png",
    crunchLevel: "Classic Snap",
    crunchStars: 4,
    spiceLevel: "Mild Salted",
    flavorTags: ["Pure & Simple", "Zero Spice", "Lunchbox Favorite"],
    badge: "Kids Love It 👍",
    accentColor: "#FFFDF0",
    desc: "Wholesome blanched peanuts slowly roasted to a warm golden hue and sprinkled with pure natural salt. Clean, savory, and pure energy with every single crunch.",
    kidFact: "Squirrels love peanuts so much they bury thousands of them each autumn! 🐿️",
    nutrition: {
      calories: "165 kcal",
      protein: "6.4g",
      carbs: "8g",
      fiber: "2.6g",
      fat: "11.2g"
    },
    ingredients: "Select Roasted Peanuts, Edible Vegetable Oil, Pure Iodized Salt."
  },
  {
    id: "moong-dal",
    name: "Nimco's Crispy Salted Moong Dal",
    tagline: "Golden Yellow Pulses - Light as Air & Super Crisp!",
    category: "dals",
    categoryLabel: "Crunchy Dals",
    price: 5,
    packWeight: "35g",
    image: "assets/moong_dal.png",
    crunchLevel: "Light Crunch",
    crunchStars: 5,
    spiceLevel: "Mild Salted",
    flavorTags: ["Protein Rich", "Light & Crisp", "Zero Cholesterol"],
    badge: "Mom Approved ✔️",
    accentColor: "#FFF9DB",
    desc: "Husked petite yellow moong dal lentils fried to an ethereal lightness and dusted with rock salt. It's so light and crispy you can munch handfuls without feeling heavy!",
    kidFact: "Moong dal is packed with natural plant proteins that help you grow taller and stronger! 🌿💪",
    nutrition: {
      calories: "135 kcal",
      protein: "5.1g",
      carbs: "17g",
      fiber: "2.2g",
      fat: "6.0g"
    },
    ingredients: "Green Gram Split (Moong Dal), Edible Vegetable Oil, Iodized Salt, Black Pepper."
  },
  {
    id: "chana-dal",
    name: "Nimco's Spicy Chana Dal",
    tagline: "Hearty Bengal Gram with Chatpata Zing",
    category: "dals",
    categoryLabel: "Crunchy Dals",
    price: 5,
    packWeight: "35g",
    image: "assets/chana_dal.png",
    crunchLevel: "Firm Crunch",
    crunchStars: 5,
    spiceLevel: "Chatpata Zing",
    flavorTags: ["Fiber Rich", "Grandma Approved", "Hearty Munch"],
    badge: "Nutritious 🌾",
    accentColor: "#FFF3DC",
    desc: "Golden split Bengal gram fried until delightfully crunchy and seasoned with spicy red chili, tart dry mango, and fragrant garam masala.",
    kidFact: "Chana dal has been eaten in India for over 4,000 years! Even ancient kings enjoyed it! 👑",
    nutrition: {
      calories: "140 kcal",
      protein: "5.4g",
      carbs: "16g",
      fiber: "3.1g",
      fat: "6.8g"
    },
    ingredients: "Split Bengal Gram (Chana Dal), Edible Vegetable Oil, Red Chilli Powder, Dry Mango, Cumin, Black Salt."
  },
  {
    id: "hing-chana",
    name: "Nimco's Hing Roasted Chana",
    tagline: "Aromatic Asafoetida & Roasted Chickpea Power",
    category: "dals",
    categoryLabel: "Crunchy Dals",
    price: 5,
    packWeight: "35g",
    image: "assets/hing_chana.png",
    crunchLevel: "Solid Crunch",
    crunchStars: 5,
    spiceLevel: "Aromatic Savory",
    flavorTags: ["Good For Tummy", "Roasted Chana", "Digestive Hing"],
    badge: "Tummy Friendly 🌿",
    accentColor: "#F4F7EB",
    desc: "Crunchy roasted brown chickpeas flavored with authentic Hing (asafoetida) and warm ground spices. Fantastic for digestion and packed with clean stamina.",
    kidFact: "Hing is a super spice that makes your tummy feel happy and light after eating snacks! 🎈",
    nutrition: {
      calories: "130 kcal",
      protein: "5.6g",
      carbs: "18g",
      fiber: "4.0g",
      fat: "4.2g"
    },
    ingredients: "Roasted Bengal Gram (Chana), Pure Asafoetida (Hing), Rock Salt, Black Pepper, Cumin, Light Vegetable Oil."
  },
  {
    id: "matar",
    name: "Nimco's Chatpata Green Peas (Matar)",
    tagline: "Sweet Green Peas with a Tangy Crunch!",
    category: "dals",
    categoryLabel: "Crunchy Dals",
    price: 5,
    packWeight: "35g",
    image: "assets/Matar.png",
    crunchLevel: "Crispy Pop",
    crunchStars: 4,
    spiceLevel: "Tangy Chatpata",
    flavorTags: ["Green Goodness", "Tangy Peas", "Fun Color"],
    badge: "Kid Favorite 🟢",
    accentColor: "#E8F8EE",
    desc: "Vibrant sweet green peas dehydrated and fried to crisp perfection, then dusted with tangy chaat spices. Pop them into your mouth one by one for continuous smiles!",
    kidFact: "Green peas are naturally sweet because plants store sunlight energy inside them as glucose! ☀️",
    nutrition: {
      calories: "128 kcal",
      protein: "4.2g",
      carbs: "17g",
      fiber: "3.6g",
      fat: "4.8g"
    },
    ingredients: "Dehydrated Green Peas, Edible Vegetable Oil, Dry Mango Powder, Cumin, Iodized Salt, Chaat Masala."
  },
  {
    id: "tikha-mitha-mix",
    name: "Nimco's Tikha Mitha Mixture",
    tagline: "The Perfect Balance of Sweet & Spicy Thrill!",
    category: "mixes",
    categoryLabel: "Chatpata & Mixes",
    price: 5,
    packWeight: "35g",
    image: "assets/tikha_mitha_mix.jpeg",
    crunchLevel: "Full Spectrum Crunch",
    crunchStars: 5,
    spiceLevel: "Mild Spicy & Sweet",
    flavorTags: ["Best Value", "Party Mix", "Flavor Explosion"],
    badge: "Family Pack 🎉",
    accentColor: "#FFEFE5",
    desc: "A timeless Indian favorite blending fiery spiced sev ribbons, tender sweet boondi drops, crisp lentils, and curry leaf flakes. Hits every tastebud simultaneously!",
    kidFact: "The word Namkeen comes from 'Namak' (salt), but recipes like this add sweet drops for magic! ✨",
    nutrition: {
      calories: "148 kcal",
      protein: "3.4g",
      carbs: "19g",
      fiber: "2.0g",
      fat: "7.2g"
    },
    ingredients: "Gram Flour, Rice Flakes, Sweet Drops (Boondi), Groundnuts, Curry Leaves, Sugar, Red Chilli, Spices, Vegetable Oil."
  },
  {
    id: "corn-mix",
    name: "Nimco's Golden Corn Flake Mix",
    tagline: "Sun-Dried Corn Crisp with Roasted Nuts",
    category: "mixes",
    categoryLabel: "Chatpata & Mixes",
    price: 5,
    packWeight: "30g",
    image: "assets/corn_mix.jpeg",
    crunchLevel: "Feather Crisp",
    crunchStars: 4,
    spiceLevel: "Tangy Mild",
    flavorTags: ["Golden Corn", "Lunchbox Special", "Sweet & Salty"],
    badge: "Morning Crunch 🌽",
    accentColor: "#FFFBE6",
    desc: "Crisp puffed corn flakes blended with crunchy roasted groundnuts, seasoned lightly with chatpata masala. Incredible crunch that doesn't poke your mouth!",
    kidFact: "Corn was first grown in the Americas and can be made into over 3,000 different yummy foods! 🌽",
    nutrition: {
      calories: "138 kcal",
      protein: "3.0g",
      carbs: "19g",
      fiber: "2.4g",
      fat: "6.1g"
    },
    ingredients: "Corn Flakes, Peanuts, Puffed Gram, Edible Vegetable Oil, Sugar, Amchur, Cumin, Black Salt."
  },
  {
    id: "dal-chawal",
    name: "Nimco's Dal Chawal Crispy Crunch",
    tagline: "India's Comfort Food Turned Into a Fun Snack!",
    category: "mixes",
    categoryLabel: "Chatpata & Mixes",
    price: 5,
    packWeight: "30g",
    image: "assets/dal_chawal.jpeg",
    crunchLevel: "Breezy Snap",
    crunchStars: 4,
    spiceLevel: "Savory Mild",
    flavorTags: ["Comfort Food", "Air Light", "Anytime Munch"],
    badge: "Innovative 🍚",
    accentColor: "#F4F6F9",
    desc: "A delightful reimagining of India's favorite comfort staple! Puffed golden rice crispies tossed with lightly roasted pulses and savory seasonings.",
    kidFact: "Rice and Dal together make a complete protein, which is like building blocks for your brain! 🧠",
    nutrition: {
      calories: "122 kcal",
      protein: "3.2g",
      carbs: "20g",
      fiber: "1.8g",
      fat: "4.0g"
    },
    ingredients: "Puffed Rice, Roasted Lentils, Chickpea Flour crisps, Refined Palmolein Oil, Salt, Turmeric, Cumin."
  },
  {
    id: "salted-pope",
    name: "Nimco's Salted Pope Crispies",
    tagline: "Puffy Light Tubes with Mellow Salt",
    category: "mixes",
    categoryLabel: "Chatpata & Mixes",
    price: 5,
    packWeight: "25g",
    image: "assets/salted_pope.jpeg",
    crunchLevel: "Melt-In-Mouth",
    crunchStars: 4,
    spiceLevel: "Zero Spice",
    flavorTags: ["Finger Tubes", "Fun To Play", "Baby Friendly"],
    badge: "Super Fun 🤸",
    accentColor: "#F0F4FF",
    desc: "Crispy tubular finger puffs that kids adore popping onto their fingertips before munching! Light as a feather and delicately salted.",
    kidFact: "Playing ring-toss on your fingers with tubular snacks is approved by 10 out of 10 happy kids! 😄",
    nutrition: {
      calories: "110 kcal",
      protein: "2.1g",
      carbs: "18g",
      fiber: "1.2g",
      fat: "4.2g"
    },
    ingredients: "Wheat Flour, Corn Starch, Vegetable Oil, Natural Sea Salt, Leavening agents."
  },
  {
    id: "jeera-papad",
    name: "Nimco's Traditional Jeera Papad",
    tagline: "Sun-Dried Crispiness with Whole Cumin Seeds",
    category: "papad",
    categoryLabel: "Papad & Treats",
    price: 10,
    packWeight: "100g",
    image: "assets/jeera-papad.png",
    crunchLevel: "Extreme Crisp",
    crunchStars: 5,
    spiceLevel: "Aromatic Cumin",
    flavorTags: ["Sun Dried", "Whole Jeera", "Roast or Fry"],
    badge: "Royal Feast 🫓",
    accentColor: "#FFFDF2",
    desc: "Handmade authentic thin lentil wafers generously studded with whole fragrant cumin seeds. Roast over an open flame for smoky crunch or fry for celebratory feast dinners!",
    kidFact: "Cumin seeds (Jeera) are tiny stars that help calm your tummy and add royal aroma! 🌟",
    nutrition: {
      calories: "92 kcal per pc",
      protein: "4.5g",
      carbs: "14g",
      fiber: "2.9g",
      fat: "0.8g"
    },
    ingredients: "Urad Dal Flour, Moong Dal Flour, Whole Cumin Seeds (Jeera), Black Pepper, Asafoetida, Papad Khar, Edible Salt."
  }
];

if (typeof window !== 'undefined') {
  window.NIMCO_PRODUCTS = NIMCO_PRODUCTS;
}
